# Generated by Django 3.0.8 on 2023-09-01 11:44

import django.core.validators
from django.db import migrations, models
import kyc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z-]+$', 'Only alphabetic characters and hyphens are allowed.'), kyc.models.validate_min_length])),
                ('lastname', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z-]+$', 'Only alphabetic characters and hyphens are allowed.'), kyc.models.validate_min_length])),
                ('dateofbirth', models.DateField(validators=[kyc.models.validate_age])),
                ('address', models.CharField(max_length=255, validators=[kyc.models.validate_min_length])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
    ]
