# Generated by Django 3.0.8 on 2023-09-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='dateofbirth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='firstname',
            new_name='first_Name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='lastname',
            new_name='last_Name',
        ),
        migrations.AddField(
            model_name='register',
            name='Town',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='register',
            name='Zip_code',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='register',
            name='country',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='register',
            name='phone',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='register',
            name='state',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
