# Generated by Django 3.0.8 on 2023-09-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20230901_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Town',
            field=models.CharField(default='Town', max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='country',
            field=models.CharField(default='Uganda', max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='@example.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(default='+256', max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(default='State', max_length=20),
        ),
    ]
